### ISSUE TITLE
Fix data update

### ISSUE THREAD

**Issue by starsep** [EqualStreetNames/equalstreetnames-warsaw#3]
@jbelien
The data hasn't been updated for some time.
I tried running `Update data` action manually https://github.com/EqualStreetNames/equalstreetnames-warsaw/actions/runs/4213156444/jobs/7312687870
There is 401 error so it's some permission/access issue. I don't know whether I can configure it myself.
Could you please help me?

**Comment by jbelien** [comment]
Hello @starsep ,

The automated update process stopped in May 2022 because it was looking for `.overpassql` files (see https://github.com/EqualStreetNames/equalstreetnames-warsaw/actions/runs/3599508876/jobs/6063208692#step:7:9).

This has now been fixed in #1.

But meanwhile the `ACCESS_TOKEN` organization secret had expired.
I've regenerated that token and run the update.

Everything is now back online! 🎉
